linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.Fatal'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small programs
    - execinquery       # deprecated in golangci v1.58
    - exhaustruct       # not useful for this repo (we want to rely on zero values for fields)
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomnd             # some unnamed constants are okay
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # unnecessary for small programs
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # named returns are fine, it's *bare* returns that are not
    - protogetter       # too many false positives
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude-dirs-use-default: false
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
  exclude-rules:
    - path: cmd/.*/main\.go
      linters:
        - forbidigo # log.Fatal and fmt.Print is used in some main functions
    - path: go/internal/swapi/handler\.go
      linters:
        - dupl # this file already uses generic functions to reduce duplication
               # but not a lot more can easily be done, and current state still
               # triggers this linter to complain
